name: Build / Test / Release

on:
  push:
    tags:
      - v*
      - "*-alpha"
      - "*-beta"
      - "*-new"
      - "*-preview"
    branches:
      - main
      - master
      - dev
      - release/*

jobs:
  build-scriptable-library:
    name: Build Scriptable Project
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ./src/Scriptable
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build, Test, Publish, Pack
        run: |
          dotnet restore \
            --configuration ${{ env.RELEASE_CONFIGURATION }}
          
          dotnet build \ 
            --no-logo \ 
            --no-restore \
            --configuration ${{ env.RELEASE_CONFIGURATION }}

          dotnet test --list-tests
          dotnet test \
              --no-logo
              --no-build \
              --verbosity detailed \
              --configuration ${{ env.RELEASE_CONFIGURATION }} \
              --logger "html;LogFileName=logs/scriptable-test-logfile.html" \
              --results-directory results
          
          dotnet publish \
            --no-logo \
            --no-build \
            --no-self-contained \
            --configuration ${{ env.RELEASE_ONFIGURATION }}
            --output publish/no-containment/ \
            --verbosity detailed

          dotnet publish \
            --no-logo \
            --no-build \
            --no-restore \
            --self-contained \
            --configuration ${{ env.RELEASE_ONFIGURATION }}
            --output publish/self-contained \
            --verbository detailed
          
          dotnet pack \ 
            --nologo \
            --no-build \
            --no-restore \
            --include-symbols \
            --include-source \ 
            --output pack/full \
            --configuration ${{ env.RELEASE_CONFIGURATION }} \
            --force

          dotnet pack \ 
            --nologo \
            --no-build \
            --no-restore \
            --include-symbols \
            --output pack/symbols-only
            --configuration ${{ env.RELEASE_CONFIGURATION }} \
            --force

          dotnet pack \ 
            --nologo \
            --no-build \
            --no-restore \
            --include-source \
            --output pack/source-only \
            --configuration ${{ env.RELEASE_CONFIGURATION }} \
            --force

          dotnet pack \ 
              --nologo \
              --no-build \
              --no-restore \
              --output pack/no-symbols-no-source
              --configuration ${{ env.RELEASE_CONFIGURATION }} \
              --force
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: library
          path: bin/**
          if-no-files-found: error