name: Build / Test / Release


on:
  push:
    tags:
      - "v*"

env:
  DOTNET_NO_LOGO: true

jobs:
  build-scriptable-library:
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
        builder:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          
    name: Build Scriptable Project [${{ matrix.configuration }}]
    runs-on: ${{ matrix.builder }}
    env:
      RELEASE_CONFIGURATION: ${{ matrix.configuration }}
      SLN: ./src/Scriptable.sln
      PROJECT: ./src/Scriptable/Scriptable.csproj
      TEST: ./test/Scriptable.Test/Scriptable.Test.csproj

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Dotnet Restore
        run: dotnet restore "${{ env.SLN }}"

      - name: Build Scriptable Library
        run: dotnet build -c "${{ env.RELEASE_CONFIGURATION }}" "${{ env.SLN }}";
        
  test-scriptable-project:
    env:
      CONFIG: Debug
      TEST: './src/Scriptable.Test/Scriptable.Test.csproj'
    strategy:
      matrix:
        builder:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Test Scriptable Library
        if: ${{ env.RELEASE_CONFIGURATION == 'Debug' }}
        run: dotnet test --verbosity detailed -c "${{ env.RELEASE_CONFIGURATION }}" --logger "html;LogFileName=${{ env.TEST_LOGFILE }}" --results-directory "${{ env.TEST_RESULTS_DIR }}" "${{ env.SLN }}";
        env:
          TEST_LOGFILE: ./logs/scriptable-test-logfile.html
          TEST_RESULTS_DIR: ./results

      - name: Publish Scriptable Library (No Self Containment)
        if: ${{ matrix.RELEASE_CONFIGURATION = 'Release' }}
        run: |
          if [[ ! -d "${{ env.PUBLISH_PATH }}" ]]; then
              mkdir -p "${{ env.PUBLISH_PATH }}";
          fi
          
          dotnet publish \
            --no-self-contained \
            -c ${{ env.RELEASE_CONFIGURATION }}
            --output publish/no-containment/ \
            --verbosity detailed \
            "${{ env.PROJECT }}"

          echo "::set-output name=PUBLISH_PATH::${{ env.PUBLISH_PATH }}"
        env:
          PUBLISH_PATH: ./publish/no-containment

      - name: Publish Scriptable Library (Self Contained)
        run: |
          test ! -d "${{ env.PUBLISH_PATH }}" && mkdir -p "${{ env.PUBLISH_PATH }}";
          dotnet publish \
            --nologo \
            --no-build \
            --no-restore \
            --self-contained \
            --configuration "${{ env.RELEASE_CONFIGURATION }}" \
            --output "${{ env.PUBLISH_PATH }}" \
            --verbository detailed \
            "${{ env.PROJECT }}"

          echo "::set-output name=PUBLISH_PATH::${{ env.PUBLISH_PATH }}"
        env:
          PUBLISH_PATH: ./publish/self-contained

      - name: Pack Scriptable Project (Full)
        run: |
          test ! -d "${{ env.OUTPUT_PATH }}" && mkdir -p "${{ env.OUTPUT_PATH }}";
          dotnet pack \
            --nologo \
            --no-build \
            --no-restore \
            --include-symbols \
            --include-source \
            --output "${{ env.OUTPUT_PATH }}"" \
            --configuration "${{ env.RELEASE_CONFIGURATION }}" \
            --force \
            "${{ env.PROJECT }}"

          echo "::set-output name=OUTPUT_PATH::$(echo "${{ env.OUTPUT_PATH }})"
        env:
          OUTPUT_PATH: ./pack/full

      - name: Pack Scriptable Project (Symbols-Only)
        run: |
          test ! -d "${{ env.OUTPUT_PATH }}" && mkdir -p "${{ env.OUTPUT_PATH }}";
          dotnet pack \
            --nologo \
            --no-build \
            --no-restore \
            --include-symbols \
            --output
            --configuration "${{ env.RELEASE_CONFIGURATION }}" \
            --force \
            "${{ env.PROJECT }}"

          echo "::set-output name=OUTPUT_PATH::$(echo "${{ env.OUTPUT_PATH }})"
        env:
          OUTPUT_PATH: ./pack/symbols-only

      - name: Pack Scriptable Project (Source-Only)
        run: |
          test ! -d "${{ env.OUTPUT_PATH }}" && mkdir -p "${{ env.OUTPUT_PATH }}";
          dotnet pack \
            --nologo \
            --no-build \
            --no-restore \
            --include-source \
            --output "${{ env.OUTPUT_PATH }}" \
            --configuration "${{ env.RELEASE_CONFIGURATION }}" \
            --force \
            "${{ env.PROJECT }}";

          echo "::set-output name=OUTPUT_PATH::$(echo "${{ env.OUTPUT_PATH }})"
        env:
          OUTPUT_PATH: ./pack/source-only

      - name: Pack Scriptable Project (Production)
        run: |
          test ! -d "${{ env.OUTPUT_PATH }}" && mkdir -p "${{ env.OUTPUT_PATH }}";
          dotnet pack \
              --nologo \
              --no-build \
              --no-restore \
              --output "${{ env.OUTPUT_PATH }}" \
              --configuration "${{ env.RELEASE_CONFIGURATION }}" \
              --force \
              "${{ env.PROJECT }}"

          echo "::set-output name=OUTPUT_PATH::$(echo "${{ env.OUTPUT_PATH }})"
        env:
            OUTPUT_PATH: ./pack/no-symbols-no-source

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: scriptable-library
          path: |
            **/bin/**
            **/publish/**
            **/pack/**
            **/tests/logs/**
            **/tests/results/**
          if-no-files-found: error
