name: Build / Test / Release


on:
  push:
    tags:
      - "v*"

env:
  DOTNET_NO_LOGO: true

jobs:
  build-scriptable-library:
    name: Build Scriptable Project
    runs-on: ubuntu-latest
    env:
      RELEASE_CONFIGURATION: DEBUG
      PROJECT: ./src/Scriptable/Scriptable.csproj
      TEST: ./test/Scriptable.Test/Scriptable.Test.csproj
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Dotnet Restore
        run: |
         dotnet restore "${{ env.PROJECT }}"
         dotnet restore "${{ env.TEST }}"

      - name: Build Scriptable Library
        run: dotnet build --no-restore --configuration "${{ env.RELEASE_CONFIGURATION }}" "${{ env.PROJECT }}";

      #- name: List All Tests
      #  ## Disable temporarily.
      #  if: ${{ env.RELEASE_CONFIGURATION == 'DEBUG' && false }}
      #  run: dotnet test --nologo --no-build --list-tests "${{ env.TEST }}"

      - name: Test Scriptable Library
        if: ${{ env.RELEASE_CONFIGURATION == 'DEBUG' }}
        run: |
          test ! -d "${{ env.TEST_LOGFILE }}" && mkdir -p "${{ env.TEST_LOGFILE }}";
          test ! -d "${{ env.TEST_RESULTS_DIR }}" && mkdir -p "${{ env.TEST_RESULTS_DIR }}";
          dotnet test --no-build --verbosity detailed --configuration "${{ env.RELEASE_CONFIGURATION }}" --logger "html;LogFileName=${{ env.TEST_LOGFILE }}" --results-directory "${{ env.TEST_RESULTS_DIR }}" "$TEST_PROJ";
        env:
          TEST_LOGFILE: ./logs/scriptable-test-logfile.html
          TEST_RESULTS_DIR: ./results

      - name: Publish Scriptable Library (No Self Containment)
        run: |
          test ! -d "${{ env.PUBLISH_PATH }}" && mkdir -p "${{ env.PUBLISH_PATH }}";
          dotnet publish \
            --nologo \
            --no-build \
            --no-self-contained \
            --configuration ${{ env.RELEASE_CONFIGURATION }}
            --output publish/no-containment/ \
            --verbosity detailed \
            "${{ env.PROJECT }}"

          echo "::set-output name=PUBLISH_PATH::$(echo "${{ env.PUBLISH_PATH }})"
        env:
          PUBLISH_PATH: ./publish/no-containment
          
      - name: Publish Scriptable Library (Self Contained)
        run: |
          test ! -d "${{ env.PUBLISH_PATH }}" && mkdir -p "${{ env.PUBLISH_PATH }}";
          dotnet publish \
            --nologo \
            --no-build \
            --no-restore \
            --self-contained \
            --configuration "${{ env.RELEASE_CONFIGURATION }}" \
            --output "${{ env.PUBLISH_PATH }}" \
            --verbository detailed \
            "${{ env.PROJECT }}"
          
          echo "::set-output name=PUBLISH_PATH::$(echo "${{ env.PUBLISH_PATH }})"
        env:
          PUBLISH_PATH: ./publish/self-contained

      - name: Pack Scriptable Project (Full)
        run: |
          test ! -d "${{ env.OUTPUT_PATH }}" && mkdir -p "${{ env.OUTPUT_PATH }}";
          dotnet pack \
            --nologo \
            --no-build \
            --no-restore \
            --include-symbols \
            --include-source \
            --output "${{ env.OUTPUT_PATH }}"" \
            --configuration "${{ env.RELEASE_CONFIGURATION }}" \
            --force \
            "${{ env.PROJECT }}"

          echo "::set-output name=OUTPUT_PATH::$(echo "${{ env.OUTPUT_PATH }})"
        env:
          OUTPUT_PATH: ./pack/full

      - name: Pack Scriptable Project (Symbols-Only)
        run: |
          test ! -d "${{ env.OUTPUT_PATH }}" && mkdir -p "${{ env.OUTPUT_PATH }}";
          dotnet pack \
            --nologo \
            --no-build \
            --no-restore \
            --include-symbols \
            --output 
            --configuration "${{ env.RELEASE_CONFIGURATION }}" \
            --force \
            "${{ env.PROJECT }}"

          echo "::set-output name=OUTPUT_PATH::$(echo "${{ env.OUTPUT_PATH }})"
        env:
          OUTPUT_PATH: ./pack/symbols-only

      - name: Pack Scriptable Project (Source-Only)
        run: |
          test ! -d "${{ env.OUTPUT_PATH }}" && mkdir -p "${{ env.OUTPUT_PATH }}";
          dotnet pack \
            --nologo \
            --no-build \
            --no-restore \
            --include-source \
            --output "${{ env.OUTPUT_PATH }}" \
            --configuration "${{ env.RELEASE_CONFIGURATION }}" \
            --force \
            "${{ env.PROJECT }}";

          echo "::set-output name=OUTPUT_PATH::$(echo "${{ env.OUTPUT_PATH }})"
        env:
          OUTPUT_PATH: ./pack/source-only

      - name: Pack Scriptable Project (Production)
        run: |
          test ! -d "${{ env.OUTPUT_PATH }}" && mkdir -p "${{ env.OUTPUT_PATH }}";
          dotnet pack \
              --nologo \
              --no-build \
              --no-restore \
              --output "${{ env.OUTPUT_PATH }}" \
              --configuration "${{ env.RELEASE_CONFIGURATION }}" \
              --force \
              "${{ env.PROJECT }}"

          echo "::set-output name=OUTPUT_PATH::$(echo "${{ env.OUTPUT_PATH }})"
        env:
            OUTPUT_PATH: ./pack/no-symbols-no-source

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: scriptable-library
          path: |
            **/bin/**
            **/publish/**
            **/pack/**
            **/tests/logs/**
            **/tests/results/**
          if-no-files-found: error
